### PR TITLE
Add missing registers stub

### PR DESCRIPTION
**Pull request by malleoz**
Noticed this was missing.

Besides this, I do want to say that we love your work on this fork.  We've made a separate fork and have been tailoring it to the needs of the Mario Kart Wii TAS community. In the near future I would like to see if our team could share changes we've made to our fork and merge them into yours if desired. I don't know if your goal is to merge this into upstream, but sharing our changes can only benefit everyone involved!

### CODE REVIEW

**Review by Felk — CHANGES_REQUESTED** [review]
Thank you! I didn't even know these were missing lol. One thing, can you add this as another import to `__init__.pyi` please?

**Comment by Felk** [comment]
> Besides this, I do want to say that we love your work on this fork.

Thank you! I'm glad it's useful!

> We've made a separate fork and have been tailoring it to the needs of the Mario Kart Wii TAS community. In the near future I would like to see if our team could share changes we've made to our fork and merge them into yours if desired.

Yes, that'd be awesome!

> I don't know if your goal is to merge this into upstream, but sharing our changes can only benefit everyone involved!

I don't want to rule out an upstream merge (in fact, I did try once and that influenced the current code structure a lot), but right now I'm quite content with not doing that because it requires a significant amount of work to get things into a state where the upstream maintainers would consider merging it. And I'm not sure I'll be able to pour in that effort, at least not right now.

**Comment by malleoz** [comment]
Done!

**Comment by Felk** [comment]
LGTM! Thank you very much!

**Pull request merged**
